version: "3.9"

services:
  api:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb+srv://admin:cadastro123@cluster0.hctjvsg.mongodb.net/CadastroDispositivos?retryWrites=true&w=majority&appName=Cluster0

  mongo:
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
